project_id = "ugmvhuxcncfwbehjlwbe"

[functions.create-student]
verify_jwt = true

[functions.send-study-reminder]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = true

[functions.send-nurturing-email]
verify_jwt = false

[functions.send-admin-notification-email]
verify_jwt = true
